version: '3.7'

services:
  user-service:
    build: .
    restart: always
    environment:
      - APP_PORT=5000
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=users-service
    ports:
      - "5000:5000"
    command: ["/go/bin/cmd"]
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
